version: "3.9"

services:
  fithub_db:
    image: postgres:15
    container_name: fithub
    environment:
      POSTGRES_DB: "fithub"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    networks:
      - fithub-network
    ports:
      - "5469:5432"
    volumes:
      - postgres-fithub-data:/var/lib/postgresql/data

#  fithub-backend:
#    build:
#      context: .
#    container_name: fithub-backend
#    environment:
#      SERVER_PORT: 8080
#      JWT_SECRET_KEY: "s7k5n2x9r1v6y8w4z7u5i3o9l2p5n0x3r1v6y8w4z7u5i3o9l2p5n0x3"
#      SPRING_DATASOURCE_URL: "jdbc:postgresql://fithub:5432/fithub"
#      SPRING_DATASOURCE_USERNAME: "postgres"
#      SPRING_DATASOURCE_PASSWORD: "1"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - fithub_db
#    networks:
#      - fithub-network

networks:
  fithub-network:
    driver: bridge

volumes:
  postgres-fithub-data: